import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { encodeOperationQuery, executeOperation } from "../lib/operation.js";
import * as operations from "../models/operations/index.js";

export const mediaLibraryList = (client: ClientSDK, request: operations.ListMediaRequest = {}, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.list", method: "GET", path: () => "/media-library", requestSchema: operations.ListMediaRequest$outboundSchema, responseSchema: operations.ListMediaResponse$inboundSchema, query: (v) => encodeOperationQuery({}, { path: v.path }) }, options);
export const mediaLibraryFoldersList = (client: ClientSDK, request: operations.ListMediaFoldersRequest = {}, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.listFolders", method: "GET", path: () => "/media-library/folders", requestSchema: operations.ListMediaFoldersRequest$outboundSchema, responseSchema: operations.ListMediaFoldersResponse$inboundSchema, query: (v) => encodeOperationQuery({}, { path: v.path }) }, options);
export const mediaLibraryFoldersCreate = (client: ClientSDK, request: operations.CreateMediaFolderRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.createFolder", method: "POST", path: () => "/media-library/folders", requestSchema: operations.CreateMediaFolderRequest$outboundSchema, responseSchema: operations.CreateMediaFolderResponse$inboundSchema, body: (v) => v.data }, options);
export const mediaLibraryUploadsPresign = (client: ClientSDK, request: operations.PresignMediaUploadRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.presignUpload", method: "POST", path: () => "/media-library/uploads/presign", requestSchema: operations.PresignMediaUploadRequest$outboundSchema, responseSchema: operations.PresignMediaUploadResponse$inboundSchema, body: (v) => v.data }, options);
export const mediaLibraryItemsDelete = (client: ClientSDK, request: operations.DeleteMediaItemRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.deleteItem", method: "DELETE", path: () => "/media-library/items", requestSchema: operations.DeleteMediaItemRequest$outboundSchema, responseSchema: operations.DeleteMediaItemResponse$inboundSchema, body: (v) => v.data, responseType: "void", successStatus: 204 }, options);
export const mediaLibraryItemsMove = (client: ClientSDK, request: operations.MoveMediaItemRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.moveItem", method: "PATCH", path: () => "/media-library/items/move", requestSchema: operations.MoveMediaItemRequest$outboundSchema, responseSchema: operations.MoveMediaItemResponse$inboundSchema, body: (v) => v.data, responseType: "void", successStatus: 204 }, options);
export const mediaLibraryItemsRename = (client: ClientSDK, request: operations.RenameMediaItemRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.renameItem", method: "PATCH", path: () => "/media-library/items/rename", requestSchema: operations.RenameMediaItemRequest$outboundSchema, responseSchema: operations.RenameMediaItemResponse$inboundSchema, body: (v) => v.data }, options);
export const mediaLibrarySearch = (client: ClientSDK, request: operations.SearchMediaRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.search", method: "GET", path: () => "/media-library/search", requestSchema: operations.SearchMediaRequest$outboundSchema, responseSchema: operations.SearchMediaResponse$inboundSchema, query: (v) => encodeOperationQuery({}, { q: v.q, path: v.path }) }, options);
export const mediaLibrarySource = (client: ClientSDK, request: operations.GetMediaSourceRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.source", method: "GET", path: () => "/media-library/items/source", requestSchema: operations.GetMediaSourceRequest$outboundSchema, responseSchema: operations.GetMediaSourceResponse$inboundSchema, query: (v) => encodeOperationQuery({}, { path: v.path }), responseType: "bytes" }, options);
export const mediaLibraryDownload = (client: ClientSDK, request: operations.DownloadMediaRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "mediaLibrary.download", method: "POST", path: () => "/media-library/downloads", requestSchema: operations.DownloadMediaRequest$outboundSchema, responseSchema: operations.DownloadMediaResponse$inboundSchema, body: (v) => v.data, responseType: "bytes" }, options);
