import { ClientSDK, RequestOptions } from "../../lib/sdks.js";
import { encodeOperationQuery, executeOperation } from "../../lib/operation.js";
import * as operations from "../../models/operations/index.js";

export const customerMandatesList = (client: ClientSDK, request: operations.ListCustomerMandatesRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerMandates.list", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/mandates`, requestSchema: operations.ListCustomerMandatesRequest$outboundSchema, responseSchema: operations.ListCustomerMandatesResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerMandatesGet = (client: ClientSDK, request: operations.GetCustomerMandateRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerMandates.get", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/mandates/${v.id}`, requestSchema: operations.GetCustomerMandateRequest$outboundSchema, responseSchema: operations.GetCustomerMandateResponse$inboundSchema }, options);
export const customerMandatesCreate = (client: ClientSDK, request: operations.CreateCustomerMandateRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerMandates.create", method: "POST", path: (v) => `/commerce/customers/${v.customerId}/mandates`, requestSchema: operations.CreateCustomerMandateRequest$outboundSchema, responseSchema: operations.CreateCustomerMandateResponse$inboundSchema, body: (v) => v.data }, options);
export const customerMandatesUpdate = (client: ClientSDK, request: operations.UpdateCustomerMandateRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerMandates.update", method: "PATCH", path: (v) => `/commerce/customers/${v.customerId}/mandates/${v.id}`, requestSchema: operations.UpdateCustomerMandateRequest$outboundSchema, responseSchema: operations.UpdateCustomerMandateResponse$inboundSchema, body: (v) => v.data }, options);
export const customerMandatesDelete = (client: ClientSDK, request: operations.DeleteCustomerMandateRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerMandates.delete", method: "DELETE", path: (v) => `/commerce/customers/${v.customerId}/mandates/${v.id}`, requestSchema: operations.DeleteCustomerMandateRequest$outboundSchema, responseSchema: operations.DeleteCustomerMandateResponse$inboundSchema, responseType: "void", successStatus: 204 }, options);
