import { ClientSDK, RequestOptions } from "../../lib/sdks.js";
import { encodeOperationQuery, executeOperation } from "../../lib/operation.js";
import * as operations from "../../models/operations/index.js";

export const customerAddressesList = (client: ClientSDK, request: operations.ListCustomerAddressesRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerAddresses.list", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/addresses`, requestSchema: operations.ListCustomerAddressesRequest$outboundSchema, responseSchema: operations.ListCustomerAddressesResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerAddressesGet = (client: ClientSDK, request: operations.GetCustomerAddressRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerAddresses.get", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/addresses/${v.id}`, requestSchema: operations.GetCustomerAddressRequest$outboundSchema, responseSchema: operations.GetCustomerAddressResponse$inboundSchema }, options);
export const customerAddressesCreate = (client: ClientSDK, request: operations.CreateCustomerAddressRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerAddresses.create", method: "POST", path: (v) => `/commerce/customers/${v.customerId}/addresses`, requestSchema: operations.CreateCustomerAddressRequest$outboundSchema, responseSchema: operations.CreateCustomerAddressResponse$inboundSchema, body: (v) => v.data }, options);
export const customerAddressesUpdate = (client: ClientSDK, request: operations.UpdateCustomerAddressRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerAddresses.update", method: "PATCH", path: (v) => `/commerce/customers/${v.customerId}/addresses/${v.id}`, requestSchema: operations.UpdateCustomerAddressRequest$outboundSchema, responseSchema: operations.UpdateCustomerAddressResponse$inboundSchema, body: (v) => v.data }, options);
export const customerAddressesDelete = (client: ClientSDK, request: operations.DeleteCustomerAddressRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerAddresses.delete", method: "DELETE", path: (v) => `/commerce/customers/${v.customerId}/addresses/${v.id}`, requestSchema: operations.DeleteCustomerAddressRequest$outboundSchema, responseSchema: operations.DeleteCustomerAddressResponse$inboundSchema, responseType: "void", successStatus: 204 }, options);
