import { ClientSDK, RequestOptions } from "../../lib/sdks.js";
import { encodeOperationQuery, executeOperation } from "../../lib/operation.js";
import * as operations from "../../models/operations/index.js";

export const customerSubscriptionsList = (client: ClientSDK, request: operations.ListCustomerSubscriptionsRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.list", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/subscriptions`, requestSchema: operations.ListCustomerSubscriptionsRequest$outboundSchema, responseSchema: operations.ListCustomerSubscriptionsResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerSubscriptionsGet = (client: ClientSDK, request: operations.GetCustomerSubscriptionRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.get", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.id}`, requestSchema: operations.GetCustomerSubscriptionRequest$outboundSchema, responseSchema: operations.GetCustomerSubscriptionResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerSubscriptionsCreate = (client: ClientSDK, request: operations.CreateCustomerSubscriptionRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.create", method: "POST", path: (v) => `/commerce/customers/${v.customerId}/subscriptions`, requestSchema: operations.CreateCustomerSubscriptionRequest$outboundSchema, responseSchema: operations.CreateCustomerSubscriptionResponse$inboundSchema, body: (v) => v.data }, options);
export const customerSubscriptionsUpdate = (client: ClientSDK, request: operations.UpdateCustomerSubscriptionRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.update", method: "PATCH", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.id}`, requestSchema: operations.UpdateCustomerSubscriptionRequest$outboundSchema, responseSchema: operations.UpdateCustomerSubscriptionResponse$inboundSchema, body: (v) => v.data }, options);
export const customerSubscriptionsDelete = (client: ClientSDK, request: operations.DeleteCustomerSubscriptionRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.delete", method: "DELETE", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.id}`, requestSchema: operations.DeleteCustomerSubscriptionRequest$outboundSchema, responseSchema: operations.DeleteCustomerSubscriptionResponse$inboundSchema, responseType: "void", successStatus: 204 }, options);
export const customerSubscriptionsRenew = (client: ClientSDK, request: operations.RenewCustomerSubscriptionRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.renew", method: "POST", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.id}/renew`, requestSchema: operations.RenewCustomerSubscriptionRequest$outboundSchema, responseSchema: operations.RenewCustomerSubscriptionResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerSubscriptionsListTransitionProducts = (client: ClientSDK, request: operations.ListCustomerSubscriptionTransitionProductsRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.listTransitionProducts", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.subscriptionId}/transition`, requestSchema: operations.ListCustomerSubscriptionTransitionProductsRequest$outboundSchema, responseSchema: operations.ListCustomerSubscriptionTransitionProductsResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerSubscriptionsGetTransitionProduct = (client: ClientSDK, request: operations.GetCustomerSubscriptionTransitionProductRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerSubscriptions.getTransitionProduct", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/subscriptions/${v.subscriptionId}/transition/${v.productId}`, requestSchema: operations.GetCustomerSubscriptionTransitionProductRequest$outboundSchema, responseSchema: operations.GetCustomerSubscriptionTransitionProductResponse$inboundSchema, query: encodeOperationQuery }, options);
