import { ClientSDK, RequestOptions } from "../../lib/sdks.js";
import { encodeOperationQuery, executeOperation } from "../../lib/operation.js";
import * as operations from "../../models/operations/index.js";

export const customerOrdersList = (client: ClientSDK, request: operations.ListCustomerOrdersRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerOrders.list", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/orders`, requestSchema: operations.ListCustomerOrdersRequest$outboundSchema, responseSchema: operations.ListCustomerOrdersResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerOrdersGet = (client: ClientSDK, request: operations.GetCustomerOrderRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerOrders.get", method: "GET", path: (v) => `/commerce/customers/${v.customerId}/orders/${v.id}`, requestSchema: operations.GetCustomerOrderRequest$outboundSchema, responseSchema: operations.GetCustomerOrderResponse$inboundSchema, query: encodeOperationQuery }, options);
export const customerOrdersCreate = (client: ClientSDK, request: operations.CreateCustomerOrderRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerOrders.create", method: "POST", path: (v) => `/commerce/customers/${v.customerId}/orders`, requestSchema: operations.CreateCustomerOrderRequest$outboundSchema, responseSchema: operations.CreateCustomerOrderResponse$inboundSchema, body: (v) => v.data }, options);
export const customerOrdersUpdate = (client: ClientSDK, request: operations.UpdateCustomerOrderRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerOrders.update", method: "PATCH", path: (v) => `/commerce/customers/${v.customerId}/orders/${v.id}`, requestSchema: operations.UpdateCustomerOrderRequest$outboundSchema, responseSchema: operations.UpdateCustomerOrderResponse$inboundSchema, body: (v) => v.data }, options);
export const customerOrdersDelete = (client: ClientSDK, request: operations.DeleteCustomerOrderRequest, options?: RequestOptions) => executeOperation(client, request, { operationID: "commerce.customerOrders.delete", method: "DELETE", path: (v) => `/commerce/customers/${v.customerId}/orders/${v.id}`, requestSchema: operations.DeleteCustomerOrderRequest$outboundSchema, responseSchema: operations.DeleteCustomerOrderResponse$inboundSchema, responseType: "void", successStatus: 204 }, options);
